- alias: Regular thursday morning vacuum
  id: '15'
  action:
  - entity_id: vacuum.downstairs_vacuum
    service: vacuum.turn_on
  trigger:
  - above: '99'
    entity_id: sensor.downstairs_roomba_battery
    platform: numeric_state
  - at: 00:00:00
    platform: time
  condition:
  - after: 00:00:00
    before: 06:00:00
    condition: time
    weekday: thu
- action:
  - entity_id: vacuum.downstairs_vacuum
    service: vacuum.turn_off
  alias: turn off downstairs_vacuum when battery is low
  trigger:
  - platform: numeric_state
    entity_id: sensor.downstairs_roomba_battery
    below: 25
  id: '10'
- alias: Turn on Xmas lights at night
  id: '1'
  trigger:
  - platform: sun
    event: sunset
  action:
    service: switch.turn_on
    entity_id: group.holiday_lights
- alias: Turn off Xmas lights at sunrise
  id: '2'
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: switch.turn_off
    entity_id: group.holiday_lights
- alias: Turn off Xmas lights at bedtime
  id: '3'
  trigger:
  - platform: time
    at: 01:00:00
  action:
    service: switch.turn_off
    entity_id: group.holiday_lights
- alias: Greeting with lights
  id: '4'
  trigger:
  - platform: state
    entity_id: switch.indoor_outlet_controller_switch
    from: 'off'
    to: 'on'
  action:
    service: media_player.play_media
    entity_id: media_player.local_media
    data:
      media_content_id: /home/hass/sounds/Hallelujah-sound-effect.mp3
      media_content_type: music
- alias: Start vacuums when no one is home
  id: '5'
  trigger:
  - entity_id: alarm_control_panel.alarmcom
    platform: state
    to: armed_away
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.run_vacuums
- action:
  - service: lock.lock
  alias: Lockdown when alarm is set
  condition: []
  id: '1515854398697'
  trigger:
  - entity_id: alarm_control_panel.alarmcom
    from: disarmed
    platform: state
- action:
  - service: vacuum.turn_on
  alias: Start vacuums when boolean set
  condition:
  - condition: state
    entity_id: input_boolean.run_vacuums
    state: 'on'
  id: '1518673306804'
  trigger:
  - entity_id: input_boolean.run_vacuums
    from: '0'
    platform: state
    to: '1'
  - above: '99'
    entity_id: sensor.downstairs_roomba_battery
    platform: numeric_state

- id: '123456'
  alias: "Send Roku home when boolean enabled"
  action:
  - service: media_player.select_source
    entity_id: media_player.living_room,media_player.office #,media_player.master_br
    data:
      source: 'Home'
  trigger:
  - entity_id: media_player.living_room
    platform: 'state'
    to: 'playing'
#  - entity_id: media_player.master_br
#    platform: 'state'
#    to: 'playing'
  - entity_id: media_player.office
    platform: 'state'
    to: 'playing'
  - entity_id: input_boolean.tvs_off
    platform: 'state'
    to: 'on'
  condition:
  - entity_id: input_boolean.tvs_off
    condition: 'state'
    state: 'on'

- id: '234567'
  alias: "Turn on corner lamp for olivia"
  action:
  - service: switch.turn_on
    entity_id: switch.corner_lamp_switch
  trigger:
  - platform: time
    after: '06:15:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
